[package]
name = "reaper-rs-high"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

[dependencies]
c_str_macro = "1.0.2"
once_cell = "1.3.1"
reaper-rs-medium = { path = '../medium' }
reaper-rs-low = { path = '../low' }
# TODO Use crates.io version
rxrust = { path = '../../lib/rxRust' }
# TODO Use crates.io version
helgoboss-midi = { path = '../../../helgoboss-midi-rs' }
regex = "1.3.4"
slog = "2.5.2"
slog-stdlog = "4.0.0"
slog-term = "2.5.0"
num_enum = "0.4.2"