[package]
name = "reaper-rs-medium"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

[dependencies]
c_str_macro = "1.0.2"
derive_more = "0.99.5"
reaper-rs-low = { path = '../low' }
# TODO-medium Use crates.io version
helgoboss-midi = { path = '../../../helgoboss-midi-rs'}
num_enum = { version = "0.4.2"}
enumflags2 = { version = "^0.6", features = ["not_literal"] }