[package]
name = "reaper-rs-macros"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"

[dependencies]
quote = "1.0.2"
syn = { version = "1.0.14", features = ["full"] }

[lib]
proc-macro = true