on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI macOS

jobs:
  check:
    name: Check
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-05-15
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.7
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-05-15
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --nocapture
      - uses: actions/upload-artifact@v2
        with:
          name: test-plug-ins
          path: target/debug/*.dylib

  clippy:
    name: Clippy
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-05-15
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
