[package]
name = "reaper-rs-test-vst-plugin"
version = "0.1.0"
authors = ["Benjamin Klum <benjamin.klum@helgoboss.org>"]
edition = "2018"


[dependencies]
reaper-rs = { path = "../main" }
c_str_macro = "1.0.2"
vst = "0.2.0"

[lib]
name = "reaper_rs_test_vst_plugin"
crate-type = ["cdylib"]